name: Book

on:
  push:
    branches: ["main-gm"]
    paths:
      - "docs/**"
      - ".github/workflows/book.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  book:
    uses: globusmedical/gm-github-actions/.github/workflows/mdbook-build.yml@mdbook-build/v1
    with:
      book-directory: docs
      book-name: buffrs
      deploy-to-pages: true
      check-links: false
